version: "3.4"
services:
  master:
    hostname: master
    image: jkhlr/pytorch-mpi
    ports:
      - 127.0.0.1:22:22
    networks:
      - net
    volumes:
      - ./src:/home/pi/src
      - ./dataset:/home/pi/dataset
  slave:
    hostname: slave
    image: jkhlr/pytorch-mpi
    networks:
      - net
    volumes:
      - ./src:/home/pi/src
      - ./dataset:/home/pi/dataset

networks:
  net:
    driver: bridge