scp -r src/ray pi@pi01.local:~/susml/emanuel_tobias/
scp -r src/ray pi@pi02.local:~/susml/emanuel_tobias/
scp -r src/ray pi@pi03.local:~/susml/emanuel_tobias/
scp -r src/ray pi@pi04.local:~/susml/emanuel_tobias/
scp -r src/ray pi@pi05.local:~/susml/emanuel_tobias/
scp -r src/ray pi@pi06.local:~/susml/emanuel_tobias/
scp -r src/ray pi@pi07.local:~/susml/emanuel_tobias/
scp -r src/ray pi@pi08.local:~/susml/emanuel_tobias/
scp -r src/ray pi@pi09.local:~/susml/emanuel_tobias/
scp -r src/ray pi@pi10.local:~/susml/emanuel_tobias/
scp -r src/ray pi@pi11.local:~/susml/emanuel_tobias/
scp -r src/ray pi@pi12.local:~/susml/emanuel_tobias/